# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
	desc "Bump version. Options: patch, minor, major"
	lane :version_bump do |options|
		ensure_git_status_clean

  	version_number = increment_version_number_in_plist(
      xcodeproj: './{PROJECT_NAME}.xcodeproj',
      scheme: '{PROJECT_NAME}',
      bump_type: options[:type],
    )

	git_commit(path: "./{PROJECT_NAME}/Info.plist", message: "Version bump to: #{version_number}")
  	add_git_tag(tag: "#{version_number}")
  	{GIT_PUSH_CONFIGURATION}
	end

	#### Tests ####
	desc "Run tests"
	lane :tests do
  	run_tests(scheme: "{PROJECT_NAME}Tests")
	end

	{SWIFTLINT_LANE}

	#### Build ####
	lane :beta do
  	ensure_git_status_clean
  	increment_build_number(xcodeproj: "{PROJECT_NAME}.xcodeproj")
  	build_app(scheme: "{PROJECT_NAME}")
  	commit_version_bump(xcodeproj: "{PROJECT_NAME}.xcodeproj")
  	add_git_tag
  	push_to_git_remote
	end
end